
--- 
- name: "Download the pycollector package"
  git: 
    dest: $HOME/pycollectdsubscriber
    repo: "https://github.com/doc-vu/pycollectdsubscriber.git"
    force: yes

- name: install the pre-requisites
  shell: sh install_dependency.sh
  args:
    chdir: $HOME/pycollectdsubscriber
  become: yes

- name: install the pre-requisites
  shell: virtualenv -p python3 venv
  args:
    chdir: $HOME/pycollectdsubscriber

- pip:
    virtualenv: $HOME/pycollectdsubscriber/venv
    requirements: $HOME/pycollectdsubscriber/requirement.txt
    
- name: "Copy the JSON files for AMQP and InfluxDB 1 of 2"
  # notify: "collectd restart"
  template: src=amqp_settings.json.j2 dest=$HOME/pycollectdsubscriber/amqp_settings.json

- name: "Copy the JSON files for AMQP and InfluxDB 2 of 2"
  # notify: "collectd restart"
  template: src=influx_settings.json.j2 dest=$HOME/pycollectdsubscriber/influx_settings.json

- name: Start The Program
  shell: ./venv/bin/python -u parsingthread.py > nohuplog.txt &
  args:
    chdir: $HOME/pycollectdsubscriber
